apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: efk-stack 
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Storage.path  /var/log/flb-storage/
        Storage.sync  Normal
        Storage.checksum off
        Storage.backlog.mem_limit 1G
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE filter-multiline.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE output-file.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*
        DB                /var/log/flb_kube.db
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Refresh_Interval  10
        Read_From_Head    true
        Multiline.parser  docker
        Storage.type      filesystem

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format true
        Logstash_Prefix_Key kubernetes['pod_name'] 
        Logstash_DateFormat %Y.%m.%d
        Retry_Limit     False
   
  output-file.conf: |
    [OUTPUT]
        Name            file
        Match           kube.*
        #Format          csv
        Format          template
        Template        {time} {log}
        #Path            /data/sjjeon/logs/2022-11-24
        Workers         12

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Offset +0900
        Time_Keep   Off
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log     do_next
        Decode_Field      json       log

  filter-multiline.conf: |
    [FILTER]
        Name                  multiline
        Match                 kube.*
        Multiline.key_content log
        Multiline.parser      python

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       data 
        Keep_Log            Off

