apiVersion: v1
kind: Service
metadata:
  namespace: efk-stack 
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: webinterface
    targetPort: 5601
    nodePort: 30561
  selector:
    app: kibana
