apiVersion: v1
kind: Service
metadata:
  namespace: efk-stack  
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920
    name: client
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: client
