apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Storage.path  /var/log/flb-storage/
        Storage.sync  Normal
        Storage.checksum off
        Storage.backlog.mem_limit 1G
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE filter-multiline.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-rewrite.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE output-stdout.conf
    @INCLUDE output-file.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Exclude_Path      /var/log/containers/kube*, /var/log/containers/etcd*, /var/log/containers/coredns*, /var/log/containers/nvidia*, /var/log/containers/elasticsearch*, /var/log/containers/kibana*, /var/log/containers/fluent*, /var/log/containers/mq*, /var/log/containers/agc*, /var/log/containers/metric*
        Path              /var/log/containers/*
        DB                /var/log/flb_kube.db
        #Tag               inference.*               
        Tag               kube.*
        #Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Mem_Buf_Limit     5MB
        Refresh_Interval  10
        Read_From_Head    true
        Multiline.parser  docker
        Storage.type      filesystem

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format true
        Logstash_Prefix_Key kubernetes['pod_name'] 
        Retry_Limit     False
        #Generate_ID         On
        #Replace_Dots        On
        #Suppress_Type_Name  On
 
  output-stdout.conf: |
    [OUTPUT]
        Name            stdout
        Match           kube.*

  output-file.conf: |
    [OUTPUT]
        Name            file
        Match           i-*
        Format          template
        Template        {log}
        #File            kubernetes['pod_name'].log
        Path            /data/agc/logs

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log     do_next
        Decode_Field      json       log

  filter-rewrite.conf: |
    [FILTER]
        Name                  rewrite_tag
        Match                 kube.*
        Rule                  $log (.*) $TAG[4] false
        Emitter_Name          emitter

  filter-multiline.conf: |
    [FILTER]
        Name                  multiline
        Match                 kube.*
        Multiline.key_content log
        Multiline.parser      python

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        #Match               kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        #Kube_Tag_Prefix     kube.
        Merge_Log           On
        Merge_Log_Key       data 
        #K8S-Logging.Parser  On
        #K8S-Logging.Exclude On
        Keep_Log            Off

