---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: efk-stack
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "127.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf:
    input {
      beats {
        port => 5044
      }
    }

    filter {
      ruby {
        code => "event['date_index'] = event.timestamp.time.localtime.strftime('%Y_%m_%d')"
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch-client.efk-stack:9200"]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: efk-stack
spec:
  replicas: 7
  selector:
    matchLabels:
      task: logging
      k8s-app: logstash
  template:
    metadata:
      labels:
        task: logging
        k8s-app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.5.0
        ports:
          - containerPort: 5044
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: config-volume
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-pipeline-volume
        - name: logs-file
          mountPath: /data/home/sjjeon/logs
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: logs-file
        hostPath:
          path: /data/home/sjjeon/logs
      securityContext:
        fsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: logging
    kubernetes.io/name: logstash
  name: logstash
  namespace: efk-stack
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: lumberjack
  selector:
    k8s-app: logstash
